version: "3.9"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
      - wp-net
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - wp-net
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - wp-net
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

networks:
  wp-net:
    name: wp-net
