version: "3.9"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build:
      context: ../..
      dockerfile: ./requirements/mariadb/Dockerfile
    restart: unless-stopped
    networks:
      - wp-net
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    image:
      mariadb

  nginx:
    container_name: nginx
    build:
      context: ../..
      dockerfile: ./requirements/nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - wp-net
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    image:
      nginx
  
  wordpress:
    container_name: wordpress
    build:
      context: ../..
      dockerfile: ./requirements/wordpress/Dockerfile
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - wp-net
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    image:
      wordpress

networks:
  wp-net:
    name: wp-net
